### ISSUE TITLE
Easy fix for retest test_unixsock fail, bind(): Operation not permitted

### ISSUE THREAD

**Issue by jimmbelll** [baresip/re#1022]
**This fix works:**

re/test/unixsock.c, row 43:
`	re_snprintf(socket, sizeof(socket), "unix:/tmp/http_%s.sock", filename);`

It could be that I'm building from within a cifs mount, so creating a unix socket there is verboten.

_Originally posted by @jimmbelll in https://github.com/baresip/re/discussions/1021#discussioncomment-7711285_

**Comment by jimmbelll** [comment]
See also [Issue #1020 ](https://github.com/baresip/re/issues/1020)

**Comment by sreimers** [comment]
Running retest from a CIFS mount is nothing we support, right. But writing test data should not be outside the directory, since `/tmp` does not exist on all platforms (AF_UNIX is also supported by windows) or has other restrictions (mount options) too.
