### ISSUE TITLE
Wrong value in sizeof (re/src/http/server.c)

### ISSUE THREAD

**Issue by akscf** [baresip/re#1080]
Hi, seems there must be '*d' instead of '*conn': 
re/src/http/server.c:
```c
186: d = mem_zalloc(sizeof(*conn), verify_msg_destructor);
```

**Comment by akscf** [comment]
Tried (not sure that done it rightly, though followed the manuals, never done it before)
Can see the pull-request only in my forked repo, should it be so ?

**Comment by sreimers** [comment]
The commit looks good, but you need to open the Pull Request against the baresip/re repo.

**Comment by akscf** [comment]
seems figured out how it works )
