### ISSUE TITLE
Stateless SIP requests with TLS transport fail with EINVAL

### ISSUE THREAD

**Issue by juha-h** [baresip/re#1140]
User https://github.com/ndilieto opened this re issue against my libbaresip-android project: https://github.com/juha-h/libbaresip-android/issues/43. He also provided PR to fix it: https://github.com/juha-h/libbaresip-android/pull/42.  What is the best way to get the fix to re project?

**Comment by sreimers** [comment]
After a short look, it's maybe better to add the host param to `sip_send_conn` public api.
