### ISSUE TITLE
thread: func thrd_equal  return value error under Windows

### ISSUE THREAD

**Issue by jobo-zt** [baresip/re#1202]
Discovered during testing。
```
thread 1
thrd_t *thrd= thrd_current();

thread 2
thrd_equal(thrd, thrd_current());
```
GetThreadId(thrd_current()) return ok. but GetThreadId(thrd) return err.  thrd in thread 1
so fun thrd_equal return err.

**Comment by jobo-zt** [comment]
Reproduce the scene: https://github.com/baresip/restund/pull/8

**Comment by sreimers** [comment]
Can you try #1203

**Comment by jobo-zt** [comment]
Ok, I will test it later.

**Comment by jobo-zt** [comment]
The execution result meets expectations. OK
