### ISSUE TITLE
pthread_setname_np expects 2 arguments, 1 provided (FreeBSD 14.2)

### ISSUE THREAD

**Issue by voretaq7** [baresip/re#1228]
This looks like a re-emergence of #743 - New FreeBSD releases (at least 14.2-RELEASE, and presumably anything after) no longer have the one-argument version of `pthread_setname_np` so it's breaking in the `#ifdef` around src/cxx_supportlib/oxt/implementation.cpp line 403.

The easiest solution appears to using the Linux code for FreeBSD (move FreeBSD into the first `#ifdef`).  
That's tested and working on my systems :)

**Comment by sreimers** [comment]
> src/cxx_supportlib/oxt/implementation.cpp line 403.

This file does not belong to the libre project.
