### ISSUE TITLE
std::random_shuffle() has been deprecated since C++ 14 and is removed in C++ 17

### ISSUE THREAD

**Issue by voretaq7** [baresip/re#1229]
This causes a build failure at `src/cxx_supportlib/IOTools/IOUtils.cpp` Line 288 (FreeBSD 14.0 and later).
We've been hot-patching around it by just commenting this out and just not having the shuffle even when it's requested.  

It looks like the "right" solution these days is apparently to use std::shuffle() which takes a RNG as an argument, but we have not tested this since we're fine with un-shuffled results :)

**Comment by sreimers** [comment]
This looks like not related to libre? We have no C++ code and there is no `src/cxx_supportlib/IOTools/IOUtils.cpp`

**Comment by voretaq7** [comment]
Oops - no, I’m an idiot and had two github windows open and created issues in the wrong one!

You can kill this and my other issue and I’ll go open them in the right project :)
