### ISSUE TITLE
odict_entry union segfaults

### ISSUE THREAD

**Issue by sreimers** [baresip/re#127]
## Problem
https://github.com/baresip/baresip/blob/master/modules/mqtt/subscribe.c#L77:
```c
	debug("mqtt: handle_command:  cmd='%s', token='%s'\n",
	      oe_cmd->u.str,
	      oe_tok ? oe_tok->u.str : "");

```

If odict_entry type is a not string this produces a segfault, because  `struct odict_entry` `u` is a union and for example could be a integer value instead of a pointer. 

```c
struct odict_entry {
	struct le le, he;
	char *key;
	union {
		struct odict *odict;   /* ODICT_OBJECT / ODICT_ARRAY */
		char *str;             /* ODICT_STRING */
		int64_t integer;       /* ODICT_INT    */
		double dbl;            /* ODICT_DOUBLE */
		bool boolean;          /* ODICT_BOOL   */
	} u;
	enum odict_type type;
};
```

Its very easy to crash baresip mqtt with:

```json
/baresip/01/command/ {"command":"example","params":null,"token":11}
```

## Solution 1 - struct instead of union

```c
struct odict_entry {
	struct le le, he;
	char *key;
	struct {
		struct odict *odict;   /* ODICT_OBJECT / ODICT_ARRAY */
		char *str;             /* ODICT_STRING */
		int64_t integer;       /* ODICT_INT    */
		double dbl;            /* ODICT_DOUBLE */
		bool boolean;          /* ODICT_BOOL   */
	} u;
	enum odict_type type;
};
```

### Pros

- We can add optional type conversions (like string to int with `atoi`) if possible.
- It's backwards compatible

### Cons

- Higher memory usage (+32 Bytes per entry)
- Slower?

## Solution 2 - Hide odict_entry struct

If we hide the `struct odict_entry`, direct access with e->u.str is not possible anymore.
We can add safe getters like these:

```c
/* Odict entry Helpers */
const char *odict_entry_str(const struct odict_entry *e);
int64_t odict_entry_int(const struct odict_entry *e);
bool odict_entry_bool(const struct odict_entry *e);
```

or use `const char *odict_string(const struct odict *o, const char *key);`

### Pros

- We can enforce strict type handling

### Cons

- Not backwards compatible (breaks API)

## Solution 3 - Has to be handled by implementation 

Instead of handling this in libre and preventing misuse, we can fix all direct accesses to `u.str` and other types with strict type checks before access.

### Pros

- backwards compatible ;-)

### Cons

- It`s easy to overlook the union type and a simple json int instead of string
can result in a segfault.

@alfredh do you have a preference or another solution?

**Comment by alfredh** [comment]
no strong opinions from me ...

but I know that these helpers are in the api:

```c
/* Helpers */

const struct odict_entry *odict_get_type(const struct odict *o,
					enum odict_type type, const char *key);
const char *odict_string(const struct odict *o, const char *key);
bool odict_get_number(const struct odict *o, uint64_t *num, const char *key);
bool odict_get_boolean(const struct odict *o, bool *value, const char *key);
```

**Comment by cspiel1** [comment]
I would prefer solution 2 a little bit. It seems to be the perfect solution. Further an API change means that the compiler tells the developer where the application code has to be changed. The benefit is that a segv can be avoided.

**Comment by sreimers** [comment]
I added PR #130 for solution 2. Rewriting is not hard this helped me to update most of the retest code baresip/retest#26 (must be checked carefully afterwards):

```bash
sed -i "s/\([a-z0-9]*\)\->u\.\(key\|str\|boolean\|dbl\)/odict_entry_\2(\1)/g" src.c
sed -i "s/\([a-z0-9]*\)\->u\.integer/odict_entry_int(\1)/g" src.c
```

Maybe some setters would be nice too.

**Comment by cspiel1** [comment]
The getters look ok.

Rewrite code with `sed` is super advanced. ;-)

Do we need setters already?
Is it possible to crash a program with a call to `odict_entry_add()` somehow?

**Comment by sreimers** [comment]
I don`t know if it was used (with retest not) but I can think of this code:

```c
struct odict_entry *e;
...
e->u.integer = 32;
```
To modify a odict_entry. I think the normal way is to delete and add a new entry or build a complete new odict (for response). A crash should not possible.

**Comment by cspiel1** [comment]
Ok, then `odict_entry_set()` would combine the calls to `odict_entry_del()` and `odict_entry_add()` which would be a simpler for the user if he wants to change only parts of the odict. Currently we dont't need this, but if you like ...

The second question was a little bit off topic. What if someone calls:
```
odict_entry_add(o, "foo", ODICT_INT, "jackson");
```
The man page of `va_arg()` tells that "random erros will occur".

**Comment by sreimers** [comment]
Ah I see, hm. I would say this is not so easy to overlook since you provide a explicit type in this case, but yes bad things could happen. Maybe we can also use the setters for this:
```c
int odict_set_str(struct odict *o, const char *key, const char *str);
...
```
And assume if `key` does not exists a new entry is wanted? Or more explicit with separate functions?:

```c
int odict_add_str(struct odict *o, const char *key, const char *str);
int odict_set_str(struct odict *o, const char *key, const char *str);
...
```

**Comment by cspiel1** [comment]
Yes, if you like.

But was thinking again about this. We can't make it 100% save. There are many function with variable parameters. E.g. `re_printf()`. Maybe we should simply accept that the app/baresip developer also is responsible for the stability.

**Comment by cspiel1** [comment]
@sreimers Should we close this? Or do you plan to hide `struct odict_entry`?

**Comment by sreimers** [comment]
#130 is merged now.
