### ISSUE TITLE
backtrace_symbols  openbsd current

### ISSUE THREAD

**Issue by sreimers** [baresip/re#253]
`re` now builds fine, but `baresip` still has issues.

```
 LD      baresip
ld: error: ../re/libre.so: undefined reference to backtrace_symbols [--no-allow-shlib-undefined]
ld: error: ../re/libre.so: undefined reference to backtrace [--no-allow-shlib-undefined]
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake: *** [Makefile:319: baresip] Error 1
```

_Originally posted by @jungle-boogie in https://github.com/baresip/re/issues/201#issuecomment-1054402463_

**Comment by jungle-boogie** [comment]
Hello,

`re` successfully compiled and so did `baresip`. I'm able to launch `baresip` and make test calls.

Thanks for addressing these issues!
