### ISSUE TITLE
error: unknown type name 'thrd_t

### ISSUE THREAD

**Issue by juha-h** [baresip/re#353]
I just tried to my Android app using the latest main branches of re/rem/baresip.  libbaresip build succeesed without errors, but build of the app failed like this:
```
In file included from /usr/src/baresip-studio/app/src/main/cpp/vidisp.c:5:
In file included from /usr/src/baresip-studio/distribution.video/re/include/re.h:59:
/usr/src/baresip-studio/distribution.video/re/include/re_thread.h:69:17: error: unknown type name 'thrd_t'
```
Line 5 of vidisp.c has:
```
#include <re.h>
```
Am I missing some new include or something?

**Comment by sreimers** [comment]
Interesting It should fallback to pthread. Can you try:

 ```diff
--- a/include/re_thread.h
+++ b/include/re_thread.h
-#if defined(HAVE_THREADS)
+#if defined(HAVE_THREADS) && !defined(__STDC_NO_THREADS__)
```

**Comment by sreimers** [comment]
Is HAVE_PTHREAD maybe not defined by your app?

**Comment by juha-h** [comment]
Sebastian Reimers writes:

> Interesting It should fallback to pthread. Can you try:
> 
>  ```diff
> --- a/include/re_thread.h
> +++ b/include/re_thread.h
> -#if defined(HAVE_THREADS)
> +#if defined(HAVE_THREADS) && !defined(__STDC_NO_THREADS__)
> ```

The above patch didn't help.

**Comment by juha-h** [comment]
Sebastian Reimers writes:

> Is HAVE_PTHREAD maybe not defined by your app?

I have this PTHREAD related in the Makefile that builds libbaresip:

COMMON_FLAGS := \
	EXTRA_CFLAGS="$(CFLAGS) -DANDROID" \
	EXTRA_CXXFLAGS="$(CFLAGS) -DANDROID -DHAVE_PTHREAD" \
	EXTRA_LFLAGS="$(LFLAGS)" \
	HAVE_PTHREAD=1 \
	HAVE_PTHREAD_RWLOCK=1 \
	HAVE_LIBPTHREAD= \

and then make like this:

make libbaresip.a -C baresip $(COMMON_FLAGS) ...

That has worked fine until very recently.

Just noticed that -DHAVE_PTHREAD is not in EXTRA_CFLAGS.  I'll try if
adding that helps.

**Comment by juha-h** [comment]
When I did this, Android app was built successfully:

/* #if defined(HAVE_THREADS) */
#if 0
#include <threads.h>

#else

/* #if defined(HAVE_PTHREAD) */
#if 1

#include <pthread.h>
#include <time.h>
#define ONCE_FLAG_INIT PTHREAD_ONCE_INIT
typedef pthread_once_t once_flag;
typedef pthread_t thrd_t;
typedef pthread_cond_t cnd_t;
typedef pthread_mutex_t mtx_t;

#elif defined(WIN32)

#include <windows.h>
#define ONCE_FLAG_INIT INIT_ONCE_STATIC_INIT
typedef INIT_ONCE once_flag;
typedef HANDLE thrd_t;
typedef CONDITION_VARIABLE cnd_t;
typedef CRITICAL_SECTION mtx_t;

#endif

My Makefile is here:

https://github.com/juha-h/libbaresip-android/blob/video/Makefile

**Comment by sreimers** [comment]
I think you need to add the HAVE_PTHREAD definition here:

https://github.com/juha-h/baresip-studio/blob/video/app/src/main/cpp/CMakeLists.txt

Like we did:
https://github.com/baresip/re/blob/1defe575d2fa3c3059af688cc74df3af323b0ed7/CMakeLists.txt#L96

**Comment by juha-h** [comment]
Sebastian Reimers writes:

> I think you need to add the HAVE_PTHREAD definition here:
> 
> https://github.com/juha-h/baresip-studio/blob/video/app/src/main/cpp/CMakeLists.txt
> 
> Like we did:
> https://github.com/baresip/re/blob/1defe575d2fa3c3059af688cc74df3af323b0ed7/CMakeLists.txt#L96
> 

Before as you see, there is no compile time flags in my CMakeLists.txt,
because this file only handles linking.

Why are compile time flags now needed there?

**Comment by sreimers** [comment]
> because this file only handles linking.
You are compiling: `baresip.c vidisp.c` with libre headers here:

https://github.com/juha-h/baresip-studio/blob/f0cc3813e5458a8b324923db94a2231a7f2447e3/app/src/main/cpp/CMakeLists.txt#L125

**Comment by juha-h** [comment]
Sebastian Reimers writes:

> You are compiling: `baresip.c vidisp.c` with libre headers here:
> 
> https://github.com/juha-h/baresip-studio/blob/f0cc3813e5458a8b324923db94a2231a7f2447e3/app/src/main/cpp/CMakeLists.txt#L125

OK, thanks for help.

**Comment by juha-h** [comment]
Sebastian Reimers writes:

> I think you need to add the HAVE_PTHREAD definition here:
> 
> https://github.com/juha-h/baresip-studio/blob/video/app/src/main/cpp/CMakeLists.txt
> 
> Like we did:
> https://github.com/baresip/re/blob/1defe575d2fa3c3059af688cc74df3af323b0ed7/CMakeLists.txt#L96
> 

I added this to Android project's CMakeLists.txt:

add_definitions(-DHAVE_PTHREAD)
set(HAVE_PTHREAD ON)

and now the build worked. Still wondering, why only this particular
definition needs to be there.

**Comment by juha-h** [comment]
I don't know where these comments come from.  I haven't made them.  Perhaps my GitHub account has been hacked.

**Comment by sreimers** [comment]
Looks like a late E-Mail reply comment.

**Comment by juha-h** [comment]
Sebastian Reimers writes:

> Looks like a late E-Mail reply comment.

Yes, very late.  I checked my GitHub logins and all was fine.

**Comment by juha-h** [comment]
juha-h writes:

> Just noticed that -DHAVE_PTHREAD is not in EXTRA_CFLAGS.  I'll try if
> adding that helps.

It didn't help either.
