### ISSUE TITLE
mingw build disabled

### ISSUE THREAD

**Issue by sreimers** [baresip/re#388]
Need to be fixed for CMake build

**Comment by alfredh** [comment]
Should we consider dropping Mingw with Github workflows ?

I think the most important platforms for CI are:

- Linux
- macOS
- Windows

If we cover native Windows then I think we have cover
the majority of use cases.

**Comment by sreimers** [comment]
I have a few projects for which i need mingw support, especially because some dependencies don't have native windows compiler (msvc) support and I need static builds.
