### ISSUE TITLE
incompatible or wrong C11 Threads return value handling

### ISSUE THREAD

**Issue by DenisPolygalov** [baresip/re#429]
Hi,
the problem is the following code:

https://github.com/baresip/re/blob/4dfae418d7bd3a973ec4fba8f3eb65469758844a/src/main/main.c#L182

You assume that the success code is zero, which is not the case in FreeBSD implementation for example:
https://github.com/freebsd/freebsd-src/blob/3c9ad9398fcdf5f49114fde978b7c837b7ebbc8d/lib/libstdthreads/threads.h#L68

In the standard the value of `thrd_success` is `unspecified`:
https://en.cppreference.com/w/c/thread/thrd_errors
So I think return value of all functions related to threads.h must be explicitly compared with members of the `enum`

Note that the specific line of code in libre source code might be not the only one existed in all 3 projects (re/rem/baresip).
Multiple places where return values get checked might be affected.

Regards,
Denis.

**Comment by sreimers** [comment]
Thanks for report, I'm currently preparing some PRs to fix incorrect return value checks:

libre: https://github.com/baresip/re/pull/431
librem: TODO
retest: https://github.com/baresip/retest/pull/92
baresip: https://github.com/baresip/baresip/pull/1955

**Comment by DenisPolygalov** [comment]
Thank you very much!

**Comment by DenisPolygalov** [comment]
I am sorry to tell you this but this is not fixed (does not work de facto). Specifically here: https://github.com/baresip/re/blob/18fb84055992337767714fc9372d9280d785ab9d/src/thread/thread.c#L27 for example if `err` is not zero then later https://github.com/baresip/re/blob/18fb84055992337767714fc9372d9280d785ab9d/src/thread/thread.c#L37 `mem_deref(m);` will be called and non-zero `err` value returned ruining all the following code. The similarly wrong handling may be present in several other places, such as here: https://github.com/baresip/re/blob/18fb84055992337767714fc9372d9280d785ab9d/src/jbuf/jbuf.c#L210 (if the for loop above succeeded). I was able to find only these two.

**Comment by sreimers** [comment]
Thanks for pointing this out. I refactored the err handling: https://github.com/baresip/re/pull/476
