### ISSUE TITLE
Question about Include Guards

### ISSUE THREAD

**Issue by Naegolus** [baresip/re#473]
Is there a specific reason why there is an include guard in re.h only?

Part of the include tree:
- re.h
  - re_async.h (unguarded)
  - re_main.h (unguarded)
    - re_async.h (unguarded. Second time included) => Possible redefinitions?!

Isn't this kind of erroneous?

**Comment by sreimers** [comment]
Thanks for report, is fixed now.

**Comment by Naegolus** [comment]
Wooow. That was fast. Thanks!
