### ISSUE TITLE
Atomic API - missing symbol for GCC 4.3.5

### ISSUE THREAD

**Issue by Naegolus** [baresip/re#478]
Hello everyone,

we are using libre / baresip for quite a while now and are very happy with it. BareSIP is a very powerful SIP client. But recently we ran into quite a tricky situation. The projects libre and baresip have minimum requirements on the compiler version and C standard which is absolutely understandable. Unfortunately we are using (we have to use) a very old compiler => bfin-linux-uclibc-g++ (ADI-2014R1-RC2) 4.3.5

During compilation of baresip we get the following compiling errors

>   LD      baresip
> build-blackfin/src/audio.o: In function `stop_tx':
> src/audio.c:266: undefined reference to `___sync_val_compare_and_swap_1'
> src/audio.c:267: undefined reference to `___sync_val_compare_and_swap_1'
> build-blackfin/src/audio.o: In function `start_source':
> src/audio.c:1576: undefined reference to `___sync_val_compare_and_swap_1'
> src/audio.c:1577: undefined reference to `___sync_val_compare_and_swap_1'
> src/audio.c:1582: undefined reference to `___sync_val_compare_and_swap_1'
> build-blackfin/src/audio.o:src/audio.c:1195: more undefined references to `___sync_val_compare_and_swap_1' follow
> collect2: ld returned 1 exit status
> Makefile:325: recipe for target 'baresip' failed

It seems (I think) the reason are the recently more used atomic functions from re_atomic.h. There is a commit that makes me believe that we have a chance to make baresip compiling again, even with our dinosaur-compiler.

> commit 84113e940e1e6f4598812c8104126de6d3069894 (origin/commend56)
> Author: Andrey Semashev <andrey.semashev@gmail.com>
> Date:   Thu Aug 4 15:49:43 2022 +0300
> 
>     atomic: Added support for gcc __sync intrinsics.
>     
>     This adds support for older gcc versions that didn't support
>     __atomic intrinsics.

Do you have any advice for us? Unfortunately updating the compiler is no option :'(

**Comment by cspiel1** [comment]
The commit you mention should be the solution. Not the problem. I tested already the build successfully.

I am back from vacation. We will clarify this.

**Comment by cspiel1** [comment]
Right, compilation of baresip stops in `src/audio.c` at `rx_atomic_rlx()`.

**Comment by cspiel1** [comment]
The linker has a problem, not the compiler.
```
  LD      baresip
build-blackfin/src/audio.o: In function `stop_tx':
/home/cspiel/sipseries_uclinux/user/baresip/commend/src/audio.c:265: undefined reference to `___sync_val_compare_and_swap_1'
```

**Comment by cspiel1** [comment]
This tiny snippet builds successfully.

```c
#include <stdio.h>

long cmpxchg( long* value, long comp_val, long new_val )
{

    return __sync_val_compare_and_swap( value, comp_val, new_val );
}


int main()
{
	long a=1;
	long b=2;
	long v=3;

	cmpxchg(&v, a, b);
	printf("v=%ld\n", v);
    return 0;
}
```

Also `libbaresip.so` can be linked.
```
	make modules
	make install-shared
```

But not `baresip` main program.

**Comment by cspiel1** [comment]
We found that there is only the 4-byte version available. So:
- long, int --> `__sync_val_compare_and_swap` is expanded to `__sync_val_compare_and_swap_4` --> Ok
- char (bool) -->  `__sync_val_compare_and_swap` is expanded to `__sync_val_compare_and_swap_1` --> Missing

How should we solve this?
- Read/write should be atomic for bool in practice. So simply use the non-atomic read/write for bool and if the 1-byte version is not available?
- Copy to bool to int and back and use a mutex?
- ...

**Comment by Lastique** [comment]
The linker error indicates that the compiler has no native support for the intrinsics of the given size. The user is supposed to provide a library that will implement the necessary intrinsics. I think, this is the intended compiler extension protocol. So, your solution would be to implement such a library and add it to the linker command line.

Newer compiler versions had libatomic.a that contain some of these symbols, but I'm not sure which exactly. You should take a look if yours has one.

Another option would be to emulate 1-byte and 2-byte atomics through 4-byte ones with masking and merging the surrounding bytes. But this obviously adds a lot of complexity.

**Comment by cspiel1** [comment]
Thanks! This helps. So I close this.
