### ISSUE TITLE
IPV6 in get_resolv_dns not handled correctly

### ISSUE THREAD

**Issue by jurjen-van-dijk** [baresip/re#55]
I had an issue with the name server table being empty on some locations. It turned out that wifi routers with IPV6 addresses made get_resolv_dns in libre fail.
```
for (i=0; i<min(*n, (uint32_t)state.nscount) && !err; i++) {
		struct sockaddr_in *addr = &state.nsaddr_list[i];
		err |= sa_set_sa(&nsv[i], (struct sockaddr *)addr);
	}
```
When it goes through the list, an IPV6 address would have addr 0, and sa_set_sa will return an error. It will jump out, leaving the number of servers 0.

I made this fix and now it is working for me:
```
	err = 0;
#ifdef OPENBSD
	for (i=0; i<min(*n, (uint32_t)state.nscount) && !err; i++) {
		struct sockaddr_in *addr = &state.nsaddr_list[i];
		err |= sa_set_sa(&nsv[i], (struct sockaddr *)addr);
	}
#else
	union res_sockaddr_union *addr_union = mem_alloc(state.nscount * sizeof(union res_sockaddr_union), NULL);
	int servers = res_getservers(&state, addr_union,  state.nscount);
	
	for (i = 0; i < min(*n, (uint32_t)servers) && !err; i++) {
		if (addr_union[i].sin.sin_family == AF_INET) {
			err |= sa_set_sa(&nsv[i], (struct sockaddr *)&addr_union[i].sin);
		} else if (addr_union[i].sin6.sin6_family == AF_INET6) {
			err |= sa_set_sa(&nsv[i], (struct sockaddr *)&addr_union[i].sin6);
		} else {
			(void)re_fprintf(stderr, "Undefined family.\n");
		}
	}
	
	mem_deref(addr_union);
#endif
```
Is this a known issue? Or is something in my setup wrong that it was happening?

**Comment by sreimers** [comment]
> 	int servers = res_getservers(&state, addr_union,  state.nscount);

`res_gestservers` seems to be BSD (FreeBSD, macOS, Solaris ...) only. More details about your setup would be useful.

**Comment by jurjen-van-dijk** [comment]
I am running on iOS, and the fix works there.

**Comment by jurjen-van-dijk** [comment]
I will update the post and make a PR shortly.
