### ISSUE TITLE
Warning: ABI Check failed - bump ABI version

### ISSUE THREAD

**Issue by alfredh** [baresip/re#655]
looks like the ABI check CI is failing

is it supposed to mark the build as failed ?
the build is marked as "succes".

**Comment by sreimers** [comment]
The abidiff paths are fixed now: https://github.com/baresip/re/pull/657

Its mostly a hint to bump ABI version on release. The ABI version should not be incremented until release, to avoid big ABI numbers and jumps. Currently we break the ABI  on every release. If we plan to add more ABI stability we can make this check failing or we run this only at release.

**Comment by alfredh** [comment]
thanks!
