### ISSUE TITLE
cmake: add libre namespace export

### ISSUE THREAD

**Issue by alfredh** [baresip/re#785]
When adding libre package to VCPKG, we have found some issues:

- Header files are missing from the CMake export / config
- Namespace is not used

The feedback from the vcpkg maintainers can be found in the last comment:

https://github.com/microsoft/vcpkg/pull/30859

Regarding adding namespace, it should be possible to add
something like `libre::libre` and the application can use:

```
    find_package(re REQUIRED)
    target_link_libraries(main PRIVATE libre::libre)
```

**Comment by sreimers** [comment]
I think for namespace we can maybe use the `ALIAS` add_library option:

```cmake
add_library(libre::re ALIAS re)
```

**Comment by alfredh** [comment]
closing this in favour of tracking: https://github.com/baresip/re/pull/786
