### ISSUE TITLE
100rel broken in 2 ways

### ISSUE THREAD

**Issue by pitti98** [baresip/re#791]
The first issue is an easy one. in sipsess_reply_1xx() there's a wrong newline, causing the Content-Type header to be invisible to clients that are picky about newlines:

reliably ? "\n" : "",
change to:
reliably ? "\r\n" : "",

The other issue is that the RSeq header sometimes has wrong sequence numbers. It seems the code generates a random number for the first provisional response, and the next ones take the number from the most recently sent response found in the sess->replyl list. The problem is that the responses get removed from that list as soon as they are acked, so there is no previous response to take the sequence number from, and a new random number is generated. This causes the client on the other end to complain about "out of order" RSeq's.
I think the rseq counter should be a member of the sipsess struct.

**Comment by sreimers** [comment]
@maximilianfridrich

**Comment by maximilianfridrich** [comment]
Thanks for reporting the issue. I will provide a fix very soon.

**Comment by maximilianfridrich** [comment]
Should be fixed in https://github.com/baresip/re/pull/796.
