### ISSUE TITLE
Sec-WebSocket-Protocol header missing in Upgrade response

### ISSUE THREAD

**Issue by pitti98** [baresip/re#792]
This causes chrome, and probably other webkit-based browsers, to fail the ws connection with an error 1006.

fix: add a line to the http_reply call in websock_accept()

"Sec-WebSocket-Protocol: sip\r\n"

**Comment by sreimers** [comment]
Can you provide more details about your patch, at best a complete diff or with file and line number.

**Comment by sreimers** [comment]
Proto is not supported currently, I just opened a [PR](https://github.com/baresip/re/pull/798), this introduces a new proto specific api:

```c
websock_accept_proto(connp, "sip",....);
```

**Comment by pitti98** [comment]
As far as I see, the Sec-WebSocket-Protocol header is mandatory in both the request and the 101 response, so the functions without a protocol will never be valid, right?

**Comment by pitti98** [comment]
That pull request just adds new functions, but transp.c/http_req_handler() needs to call the new one or it still won't work.
